version: '3.7'

services:
  request-replayer:
    image: datadog/dd-trace-ci:php-request-replayer
    build:
      context: request-replayer

  mysql-dev:
    image: datadog/dd-trace-ci:php-mysql-dev-5.6
    build:
      context: mysql

  nginx-apache2:
    image: datadog/dd-trace-ci:php-nginx-apache2
    build:
      context: nginx-apache2

  dev-5.4:
    image: datadog/dd-trace-ci:php-dev-5.4
    build:
      context: development
      dockerfile: Dockerfile_54

  dev-5.6:
    image: datadog/dd-trace-ci:php-dev-5.6
    build:
      context: development
      dockerfile: Dockerfile_56

  dev-7.0:
    image: datadog/dd-trace-ci:php-dev-7.0
    build:
      context: development
      dockerfile: Dockerfile_70

  dev-7.1:
    image: datadog/dd-trace-ci:php-dev-7.1
    build:
      context: development
      dockerfile: Dockerfile_71

  dev-7.2:
    image: datadog/dd-trace-ci:php-dev-7.2
    build:
      context: development
      dockerfile: Dockerfile_72

  dev-7.3:
    image: datadog/dd-trace-ci:php-dev-7.3
    build:
      context: development
      dockerfile: Dockerfile_73

  dev-7.4:
    image: datadog/dd-trace-ci:php-dev-7.4
    build:
      context: development
      dockerfile: Dockerfile_74

  7.3-centos-7:
    image: datadog/dd-trace-ci:php-7.3-centos-7
    build:
      context: centos
      args: { CENTOS_VERSION: 7, PHP_VERSION: 73 }

  7.4-centos-7:
    image: datadog/dd-trace-ci:php-7.4-centos-7
    build:
      context: centos
      args: { CENTOS_VERSION: 7, PHP_VERSION: 74 }

  7.4-debug-alpine-3.11:
    image: datadog/dd-trace-ci:php-7.4-debug-alpine-3.11
    build:
      context: alpine
      args:
        php_version: 7.4.1
        php_url: https://www.php.net/get/php-7.4.1.tar.xz/from/this/mirror
        php_sha: 561bb866bdd509094be00f4ece7c3543ec971c4d878645ee81437e291cffc762
        php_config_args: --enable-debug
        alpine_version: 3.11

  5.4-debug-buster:
    image: datadog/dd-trace-ci:php-5.4-debug-buster
    build:
      context: buster
      target: final
      args: { VERSION: v5_4, VARIANT: debug }

  5.6-debug-buster:
    image: datadog/dd-trace-ci:php-5.6-debug-buster
    build:
      context: buster
      target: final
      args: { VERSION: v5_6, VARIANT: debug }

  7.0-debug-buster:
    image: datadog/dd-trace-ci:php-7.0-debug-buster
    build:
      context: buster
      target: final
      args: { VERSION: v7_0, VARIANT: debug }

  7.1-debug-buster:
    image: datadog/dd-trace-ci:php-7.1-debug-buster
    build:
      context: buster
      target: final
      args: { VERSION: v7_1, VARIANT: debug }

  7.2-debug-buster:
    image: datadog/dd-trace-ci:php-7.2-debug-buster
    build:
      context: buster
      target: final
      args: { VERSION: v7_2, VARIANT: debug }

  7.3-debug-buster:
    image: datadog/dd-trace-ci:php-7.3-debug-buster
    build:
      context: buster
      target: final
      args: { VERSION: v7_3, VARIANT: debug }

  7.4-debug-buster:
    image: datadog/dd-trace-ci:php-7.4-debug-buster
    build:
      context: buster
      target: final
      args: { VERSION: v7_4, VARIANT: debug }

  7.4-debug-asan-buster:
    image: datadog/dd-trace-ci:php-7.4-debug-asan-buster
    build:
      context: buster
      target: final
      args: { VERSION: v7_4, VARIANT: debug-asan }

  framework-flow:
    image: datadog/dd-trace-ci:php-framework-flow
    build:
      context: frameworks
      target: flow

  framework-laravel:
    image: datadog/dd-trace-ci:php-framework-laravel
    build:
      context: frameworks
      target: laravel

  framework-symfony:
    image: datadog/dd-trace-ci:php-framework-symfony
    build:
      context: frameworks
      target: symfony

  framework-wordpress:
    image: datadog/dd-trace-ci:php-framework-wordpress
    build:
      context: frameworks
      target: wordpress
