version: '3.7'

services:
  request-replayer:
    image: datadog/dd-trace-ci:php-request-replayer
    build:
      context: request-replayer

  mysql-dev:
    image: datadog/dd-trace-ci:php-mysql-dev-5.6
    build:
      context: mysql

  nginx-apache2:
    image: datadog/dd-trace-ci:php-nginx-apache2
    build:
      context: nginx-apache2

  dev-5.4:
    image: datadog/dd-trace-ci:php-dev-5.4
    build:
      context: development
      dockerfile: Dockerfile_54

  dev-5.6:
    image: datadog/dd-trace-ci:php-dev-5.6
    build:
      context: development
      dockerfile: Dockerfile_56

  dev-7.0:
    image: datadog/dd-trace-ci:php-dev-7.0
    build:
      context: development
      dockerfile: Dockerfile_70

  dev-7.1:
    image: datadog/dd-trace-ci:php-dev-7.1
    build:
      context: development
      dockerfile: Dockerfile_71

  dev-7.2:
    image: datadog/dd-trace-ci:php-dev-7.2
    build:
      context: development
      dockerfile: Dockerfile_72

  dev-7.3:
    image: datadog/dd-trace-ci:php-dev-7.3
    build:
      context: development
      dockerfile: Dockerfile_73

  dev-7.4:
    image: datadog/dd-trace-ci:php-dev-7.4
    build:
      context: development
      dockerfile: Dockerfile_74

  7.4-centos-7:
    image: datadog/dd-trace-ci:php-7.4-centos-7
    build:
      context: centos
      args: { CENTOS_VERSION: 7, PHP_VERSION: 74 }

  7.4-debug-alpine-3.11:
    image: datadog/dd-trace-ci:php-7.4-debug-alpine-3.11
    build:
      context: alpine

  framework-flow:
    image: datadog/dd-trace-ci:php-framework-flow
    build:
      context: frameworks
      target: flow

  framework-laravel:
    image: datadog/dd-trace-ci:php-framework-laravel
    build:
      context: frameworks
      target: laravel

  framework-symfony:
    image: datadog/dd-trace-ci:php-framework-symfony
    build:
      context: frameworks
      target: symfony

  framework-wordpress:
    image: datadog/dd-trace-ci:php-framework-wordpress
    build:
      context: frameworks
      target: wordpress
