version: '3.7'

services:
  request-replayer:
    image: docker.pkg.github.com/datadog/dd-trace-ci/php-request-replayer
    build:
      context: request-replayer

  mysql-dev:
    image: docker.pkg.github.com/datadog/dd-trace-ci/php-mysql-dev:5.6
    build:
      context: mysql
